- name: Установить зависимости для VirtualBox
  apt:
    name:
      - wget
      - ca-certificates
      - gnupg
      - linux-headers-{{ ansible_kernel }}
      - build-essential
      - dkms
    state: present
  become: yes

- name: Скачать .deb пакет VirtualBox 7.2.2
  shell: wget -O /tmp/virtualbox-7.2_7.2.2-170484~Ubuntu~noble_amd64.deb https://download.virtualbox.org/virtualbox/7.2.2/virtualbox-7.2_7.2.2-170484~Ubuntu~noble_amd64.deb
  args:
    creates: /tmp/virtualbox-7.2_7.2.2-170484~Ubuntu~noble_amd64.deb
  become: yes

- name: Установить VirtualBox 7.2 из .deb
  apt:
    deb: /tmp/virtualbox-7.2_7.2.2-170484~Ubuntu~noble_amd64.deb
  become: yes

- name: Добавить пользователя в группу vboxusers
  user:
    name: "{{ ansible_user_id }}"
    groups: vboxusers
    append: yes
  become: yes